int **carregarGrafo(int *n);
int validarGrafo(int **matriz, int tamanho);
int **criarMatriz(int linhas, int colunas);
int **adicionaAresta(int linha, int coluna, int **matriz);
void imprimeMatriz(int **matriz, int tamanho);
int numeroArestas(int **matriz, int tamanho);
void lacos(int **matriz, int tamanho);
void arestasMultiplas(int **matriz, int tamanho);
int grauV(int **matriz, int vertice, int tamanho);
int somagrau(int **matriz, int tamanho);
void isolados(int **matriz, int tamanho);
void verticesImpar(int **matriz, int tamanho);
void teoremaArestas(int **matriz, int tamanho);
void grafoSimples(int **matriz, int tamanho);
void grafoCompleto(int **matriz, int tamanho);
void grafoRegular(int **matriz, int tamanho);
void passeio(int **matriz, int tamanho);
int **removerAresta(int **matriz, int tamanho);
int **removerVertice(int **matriz, int *tamanho);
void salvarGrafo(int **matriz, int tamanho);
void liberaMatriz(int **matriz, int a);